
# SEO settings
title: Albert
description: "I am a biostatistics PhD student at the Johns Hopkins Bloomberg School of Public Health."
keywords: ""
url: http://albert-kuo.me
baseurl: null

google_analytics:
repo: http://github.com/albertkuo

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

paginate: 3
paginate_path: "/page/:num/"
comments: true

destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Albert Kuo
  job      : a (soon to be) PhD student
  bio      : "Studying biostatistics at Johns Hopkins University."
  thumb    : /files/me.jpg
  email    : albertkuo8@gmail.com
  url      : http://albert-kuo.me
  github   : http://github.com/albertkuo
  linkedin : http://linkedin.com/in/albertokuo

gems:
  - bourbon # bourbon is not supported by github-pages, manually copied stylesheet
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: about
  - slug : projects
    title: projects
  - slug: misc
    title: about

include: ["_pages"]
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
