
# SEO settings
title: Albert Kuo
description: ""
keywords: ""
url: https://albertkuo.me
baseurl: null

google_analytics: UA-98438367-1
repo: https://github.com/albertkuo

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

paginate: 3
paginate_path: "/page/:num/"
comments: true

destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Albert Kuo
  job      : a PhD student
  bio      : "Studying biostatistics at Johns Hopkins University."
  thumb    : /files/me.jpg
  email    : albertkuo@jhu.edu
  url      : http://albertkuo.me
  github   : http://github.com/albertkuo
  linkedin : http://linkedin.com/in/albertokuo

plugins:
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: about
  - slug : projects
    title: projects
  - slug: misc
    title: misc

include: ["_pages"]
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "vendor"]
